Upgraded versions of plugins
HotelsDotCom/hotels-oss-parent pull request #17
Opened 2018-07-11 15:15 UTC by andreeapad

2018-07-12 08:30 UTC, massdosage requested changes
Have a look further down in the POM there are some plugins that have versions that aren't controlled by properties (e.g. the maven-dependency-plugin). Introduce properties for these and also upgrade them to the latest versions.

2018-07-12 11:10 UTC, massdosage approved these changes

2018-07-13 11:49 UTC, AnanaMJ approved these changes

2018-07-17 10:19 UTC, massdosage reviewed
Set next version to 2.2.0

2018-07-17 11:08 UTC, merged