{$test.arguments} -> test.arguments
HotelsDotCom/hotels-oss-parent pull request #7
Opened 2017-09-25 13:40 UTC by courtsVII

2017-09-25 13:52 UTC, massdosage approved these changes

2017-09-25 13:53 UTC, massdosage requested changes
It now has merge conflicts so I'll leave you to resolve those before re-approving.

2017-09-25 14:53 UTC, massdosage approved these changes
Hopefully we can get this released today, otherwise that date in the changelog is going to need to be updated ;)

2017-09-25 16:31 UTC, ddcprg approved these changes

2017-09-26 15:00 UTC, ddcprg commented on CHANGELOG.md
> +## [2.0.2] - 2017-09-25
you've got 2 approvals, just don't forget to update this date before the merge and release

2017-09-26 20:42 UTC, merged